### ISSUE TITLE
Delete lease by lease id

### ISSUE THREAD

**Issue by joshmarsh** [Optum/dce#121]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
There is currently no DELETE method implementation on the [/leases/{id} endpoint](https://github.com/Optum/dce/blob/master/modules/swagger.yaml#L470). Users must instead provide principal id and account id to the [/leases endpoint](https://github.com/Optum/dce/blob/master/modules/swagger.yaml#L360) in order to end a lease. Deleting leases by id would be more intuitive.

**Describe alternatives you've considered**

**Additional context**

**Comment by kddejong** [comment]
I think the pain of moving from the current primary index to the lease-id is worth it here.  It makes things a lot easier.  The only reason I wouldn't do this is if we were going to tackle moving to less tables.
