### ISSUE TITLE
Simplify the database layer

### ISSUE THREAD

**Issue by kddejong** [Optum/dce#135]
Simplify the database calls and logic.  Use `dynamodbav` to help marshaling and umarshaling responses.  https://docs.aws.amazon.com/sdk-for-go/api/service/dynamodb/dynamodbattribute/#Marshal

Use more PutItem to simplify logic and reduce the amount of update functions

**Comment by kddejong** [comment]
accounts is done in #195 Working through the implementation of this across the lambdas.

**Comment by marinatedpork** [comment]
@kddejong this can be closed now, yea?

**Comment by marinatedpork** [comment]
Closing as we have implemented the new DB layer with this simplified logic.
