### ISSUE TITLE
S3 Malformed Policy issue

### ISSUE THREAD

**Issue by JacobWeyer** [Optum/dce#209]
***Version information***

v0.3.0 of the CLI

***Describe the bug***

```
Error: Error putting S3 policy: MalformedPolicy: Policies must be valid JSON and the first byte must be '{'
	status code: 400, request id: 61647D60EB3D3F2B, host id: odaWMv3YYNxrPvZd7ochsjTvdpkKeKOGBSUO9ah6FaVBl3NUOe6m74fcxcqnMeckAHcnzs+rBWU=

  on init.tf line 57, in resource "aws_s3_bucket_policy" "reset_codepipeline_source_ssl_policy":
  57: 	resource "aws_s3_bucket_policy" "reset_codepipeline_source_ssl_policy" {
```

***To Reproduce***
1. Download the CLI via zip file
2. Run `DCE init`
3. Run `DCE system deploy`
4. Hit the error

***Additional context***
This is a fresh account. We had some SCP policies but moved to an org with no policies and attempted to redeploy locally via CLI.

**Comment by eschwartz** [comment]
Hey @JacobWeyer -- we're taking a look into this. We'll try to get back with more details soon

**Comment by JacobWeyer** [comment]
Our org has gone ahead and deployed v0.24.0 via TFE and didn't hit any issues with the deploy. Not sure if the above was a problem with the CLI itself or with the version the CLI tried to grab.

**Comment by joshmarsh** [comment]
Hi @JacobWeber, 

I just created a new release that includes a recent bug fix, which I suspect caused your deployment to fail. Would you mind downloading the new version and giving dce system deploy another try? 

Upon examining the logs more closely, I’m still seeing the MalformedPolicy error, even though the deployment is succeeding. I've marked this as a bug for us to look into further once https://github.com/Optum/dce-cli/pull/59 is complete.

**Comment by jacobweber** [comment]
I think you mean @JacobWeyer

**Comment by joshmarsh** [comment]
> I think you mean @JacobWeyer 

Haha, thanks for the correction @jacobweber.

**Comment by joshmarsh** [comment]
I ran `dce system deploy` several times using [cli v4.0.0](https://github.com/Optum/dce-cli/releases/tag/v0.4.0) and searched the deploy.log for MalformedPolicy. Closing this issue because the error no longer seems to be present.
