### ISSUE TITLE
Credentials Web Page Lambda not populating Cognito values in Lambda template

### ISSUE THREAD

**Issue by JacobWeyer** [Optum/dce#213]
**Version information**
- DCE v0.24.0
- Go 1.13.3 
- TFE: 12.19

**Describe the bug**
Vue template values not populating from Credentials Web Page Lambda 

**To Reproduce**
On a fresh deploy, after configuring cognito, the values aren't being populated in the index.html template via the Settings struct in the lambda.

The Settings struct specifically only has `&{us-east-1 auth api     }` set.

These ENV variables are all set, and each has a corresponding value in parameter store
```
PS_IDENTITY_POOL_ID, 
PS_USER_POOL_APP_WEB_DOMAIN, 
PS_USER_POOL_CLIENT_ID, 
PS_USER_POOL_ID, 
PS_USER_POOL_PROVIDER_NAME
```

**Expected behavior**
A Cognito login should appear and the values should not be blank in the Vue template

**Additional context**
Currently debugging, trying to further verify if its a just me problem or a problem with the specific lambda.

Each SSM parameter is being returned from SSM based on the ENV values
```
2020/01/10 18:39:06 Retrieved SSM Parameter: {
18:39:06 ARN: "arn:aws:ssm:us-east-1:114018273183:parameter/sandbox/auth/client_id",
18:39:06 LastModifiedDate: 2020-01-10 15:49:55 +0000 UTC,
18:39:06 Name: "/sandbox/auth/client_id",
18:39:06 Type: "String",
18:39:06 Value: "5m01il8aisn2dud8no5rso45uk",
18:39:06 Version: 1
18:39:06 }
```

Edit: Additional Info:
```
	// load up the values into the various settings...
        ...
	if err := cfgBldr.Dump(Settings); err != nil {
		errorMessage := fmt.Sprintf("Failed to initialize parameter store: %s", err)
		log.Fatal(errorMessage)
	}

	fmt.Println("Settings in Init")
	fmt.Println(Settings)
```

I put a print here, after the cfg builder runs with the parameter store config and the output of the settings is the same as above still `&{us-east-1 auth api     }`

**Comment by joshmarsh** [comment]
Thanks @JacobWeyer, I'm working to reproduce the issue.

**Comment by JacobWeyer** [comment]
#216 worked as intended, thank you!

**Comment by joshmarsh** [comment]
> #216 worked as intended, thank you!

Happy to help!
