### ISSUE TITLE
Principal unable to enable DyanmoDB auto scaling

### ISSUE THREAD

**Issue by eschwartz** [Optum/dce#223]
**Version information**

DCE v0.23.0

**Describe the bug**

DCE IAM principal does not have permissions to enable auto scaling in DynamoDB.
If I try to create a table with auto scaling enabled from the web console, I see:

![image](https://user-images.githubusercontent.com/1153371/72538856-0ae60600-3844-11ea-9446-342298fbb1b9.png)

Relevant SO:
https://stackoverflow.com/questions/51236686/you-do-not-have-the-required-role-to-enable-auto-scaling

Looks like it's some special IAM role property, not part of the policy itself.

**Comment by nathanagood** [comment]
We've made some changes to include `application-autoscaling:*` in the policy (see pull requests #327 and #328). However, this specific informational message is a known issue when the AWS-generated role does not exist. See https://docs.aws.amazon.com/autoscaling/application/userguide/application-auto-scaling-service-linked-roles.html. The service-linked role is created automagically by AWS when you create a table for the first time. As such, this message only appears once per account so long as the service-linked role is not deleted.
