### ISSUE TITLE
Ending a lease does not return the child account to a ready state

### ISSUE THREAD

**Issue by michaelpetersubc** [Optum/dce#231]
**Version information**
dce 0.2.1, os centos 5 go 1.13.1

**Describe the bug**
An account was added and in the ready state, a lease was created, cde auth login succeeded, used leased account successfully, ended lease - at this point the account was never returned to the ready state (though the lease was properly ended)

The last error message was admin role is not authorized to perform iam:ListRoles.
Indeed the AdminstratorAccess policy had been removed from the admin role in the child account - which makes the  authorization error seem sensible.
I suppose the question is why did dce remove the Administrator policy (using the role with remote login from the parent account does not have that effect).  

Replacing the Administrator access policy in the child account doesn't help.  The account just stays in the NotReady state for ever.

**To Reproduce**
Follow quick start guide then end the lease as described in the how to.

**Expected behavior**
The lease is terminated and the child account is cleaned up and returned to ready state

**Additional context**

**Comment by joshmarsh** [comment]
Thanks @michaelpetersubc, I’ll see if I can reproduce the issue on my end.
