### ISSUE TITLE
ENV Variables not being applied on existing TFE deployment - codebuild

### ISSUE THREAD

**Issue by JacobWeyer** [Optum/dce#269]
**Version information**
DCE v0.26.0

**Describe the bug**
I'm deploying DCE via TFE and a manual step to update the shims with the lambdas. In my terraform, I have added the following values to the module, but they're not applying to codebuild to fetch my custom AWS nuke config
```
  reset_nuke_template_bucket     = aws_s3_bucket.dce.id
  reset_nuke_template_key        = aws_s3_bucket_object.aws-nuke-config.key
```

**To Reproduce**
1. Deploy via TF as a module in another project
2. Go back and add values to the module, then redeploy TF
```
  reset_nuke_template_bucket     = aws_s3_bucket.dce.id
  reset_nuke_template_key        = aws_s3_bucket_object.aws-nuke-config.key
```
3. Check code build and it's not updated. (also does not update if you delete the codebuild project and redeploy.

**Expected behavior**
It to add the environment variables to the codebuild project

**Comment by marinatedpork** [comment]
Hi @JacobWeyer, thank you for bringing this to our attention. The reset codebuild _should_ use your provided key and bucket overrides. Before I spin up an environment to try and reproduce this, could you post your reset codebuild log output here (or a snippet of it if it contains anything sensitive)? If it is not using your provided key and bucket TF vars, then we should see something like `Using Default Nuke Configuration: ...` in the logs. Also, if you're ok with posting your TF code where you declare the DCE module and your s3 bucket, that would also be helpful - thanks.

**Comment by JacobWeyer** [comment]
Ok so yesterday when I was messing with the code and manually triggering the code build, it was populating as Stub. 

Today, after looking at some subsequent re-runs it seems to have populated properly. 

Is there something specific that would prevent a manually triggered process that would not fix the issue vs what I'm assuming is something triggered from cloudwatch?

I've had an account in NotReady since yesterday. Looks like it has retried a few times over night and now the newest builds have the env variable properly set.

**Comment by marinatedpork** [comment]
@JacobWeyer, if you don't provide a `reset_nuke_template_bucket` and `reset_nuke_template_key` bucket, then the default values (`"STUB"`) will be used. If you saw the default values appear in the environment variables when you manually created a reset CodeBuild, then it is likely that a `terraform apply` was run at some point without your `reset_nuke_template_bucket` and `reset_nuke_template_key` in place to override those defaults.

Now that the reset is using the correct values, if you go to manually create a reset CodeBuild, does it populate your key and bucket correctly?

> I've had an account in NotReady since yesterday. Looks like it has retried a few times over night and now the newest builds have the env variable properly set.

Is it failing with an error? If so, can you provide that error here? Thanks

**Comment by JacobWeyer** [comment]
I got the part that was blocking me figured out. For some reason when I manually tried to trigger the codebuild it didn't re-populate the env variables. I might not have done that right but it has been properly populating each day since from the CloudWatch triggered builds. 

I most likely didn't retry it properly so we can probably close this issue. It is trying to fetch my nuke config though.

**Comment by marinatedpork** [comment]
Excellent news @JacobWeyer. I will close this issue as the ENV variables _do_ seem to be populating. Thank you again for reaching out.
