### ISSUE TITLE
Using upstream versions of aws-nuke

### ISSUE THREAD

**Issue by rwhelan** [Optum/dce#312]
How often do you guys update the included aws-nuke version?  We are unable to sanitize accounts and add them back to the pool as aws-nuke is missing a filter we need for our Org.

I've submitted a [PR to aws-nuke](https://github.com/rebuy-de/aws-nuke/pull/483), but its unclear to me once merged, how to get that deployed via the dce deployment.

Any advice or assistance would be very appreciated!

ryan

**Comment by eschwartz** [comment]
Hey @rwhelan -- we're actually looking to contribute back a few resources to aws-nuke in the next couple weeks, so we should be keeping up to date regularly.

As far as the process for upgrading aws-nuke:
We're using [a fork of aws-nuke](https://github.com/Optum/aws-nuke) for the time being. So we would need to PR for an upstream merge from the core aws-nuke repo into Optum/aws-nuke, and then a second PR in Optum/dce to upgrade the version of aws-nuke in our go.mod file.

**Comment by rwhelan** [comment]
Thank you!
