### ISSUE TITLE
DCE Auth

### ISSUE THREAD

**Issue by rafabnunes** [Optum/dce#325]
Hello Everyone,

I'm new with DCE and recently I've deployed in my environment, but when I try to perform the command DCE Auth, open a browser with the following message {"message":"Missing Authentication Token"}. How can I fix this issue ?

OBS: I've started DCE installation with following option "Deploying DCE from the CLI".

Best Regards,

Rafael Nunes

**Comment by eschwartz** [comment]
Hi @rafabnunes , sorry for the slow response on this one.

To use the `dce auth` CLI command, you will need to connect DCE to AWS Cognito.
Try walking through the instructions [here](https://dce.readthedocs.io/en/latest/api-auth.html#using-aws-cognito), and let me know if that solves things for you.

**Comment by rafabnunes** [comment]
Hi @eschwartz,

Thanks for your reply.

I've configured Cognito like described in the document, but when I use dce auth open a browser with the following message {"message":"Missing Authentication Token"}.




Best Regards,

Rafael Nunes

**Comment by eschwartz** [comment]
Thanks @rafabnunes . I haven't experienced that before, but I can take a look.

Can you please list out which versions of DCE and dce-cli you are using?

**Comment by rafabnunes** [comment]
Hi @eschwartz 

I've been using DCE-CLI the latest version (v.0.4.0), according to the following link https://github.com/Optum/dce-cli/releases/latest/download/dce_darwin_amd64.zip

Regarding DCE, it seems like version 0.23.0. but I've checked in the repository that there are other versions more newest (v0.29.0). However the version 0.23.0 was installed when I executed the command dce system deploy in the quickstart section.

How can I upgrade DCE to the latest version ?


Regards,

Rafael Nunes

**Comment by rafabnunes** [comment]
<img width="391" alt="Screen Shot 2020-04-07 at 20 18 33" src="https://user-images.githubusercontent.com/24812827/78729006-4823d680-790f-11ea-90f2-181eaa9e3655.png">

Screenshot regarding DCE version

**Comment by eschwartz** [comment]
Hey @rafabnunes sorry we've been slow to response here. We've been spread a little thin lately.

I haven't had time yet to try to reproduce this fully. Your best bet would probably be to upgrade your version of DCE. The ability to upgrade DCE via the CLI is merged into dce-cli `master`, but not yet released. I will try to get a release out for that as soon as I can, and then get back to you.

For now, I'd recommend that you consider deploying DCE directly with Terraform, rather than using the CLI. It will give you more flexibility and control over your system:
https://dce.readthedocs.io/en/latest/terraform.html

**Comment by rafabnunes** [comment]
Hey @eschwartz don't worry, take your time. 
On last Wednesday I was able to deploy the last version with terraform. I would say now everything is working fine include authentication with AWS Cognito.

I really appreciate you help.

Thank you so much.

Rafa

**Comment by eschwartz** [comment]
Awesome, good to hear @rafabnunes . I'll close up this issue, then. Let me know if you run into any other problems.
