### ISSUE TITLE
DB Queries are not paginated

### ISSUE THREAD

**Issue by eschwartz** [Optum/dce#336]
**Version information**

DCE v0.29.0

**Describe the bug**

When attempting to delete a lease by accountId/principalId, the API mistakenly returns a `HTTP 404` response, when the requested record actually exists in the DB. 
This seems to only happen if the principal ID has more than 25 lease records in the DynDB table.

**To Reproduce**

Example API request:
```
DELETE /leases
{
  principalId: "my-user",
  acctId: "123456789012"
}
```

I have a test case the identifies the bug as living in the `pkg/data/Leases` service:

```golang
func TestTmp(t *testing.T) {
	sess, err := session.NewSession(
		&aws.Config{
			Region: aws.String("us-east-1"),
		},
	)
	require.Nil(t, err)
	dynDB := dynamodb.New(sess)

	// create the lease data service
	// as it is created in our prod depoyment
	dataSvc := Lease{
		DynamoDB:       dynDB,
		TableName:      "Leases",
		ConsistentRead: false,
		Limit:          25,
	}

	// Call the List() method, with the same parameters
	// used in the `DELETE /leases` controller
	res, err := dataSvc.List(&lease.Lease{
		AccountID: aws.String("123456789012"),
		PrincipalID: aws.String("my-user"),
	})
	require.Nil(t, err)

	// The record _does_ in fact exist in the DB,
	// so this should return a result, but it does not.
	leases := []lease.Lease(*res)
	require.Len(t, leases, 1)
}
```

I can run this against my DCE AWS account, to reproduce the error.

However, if I change the `Limit` parameter on our Lease data service to `100`, this test passes. So it looks like it checks the first 25 records in the matching PrincipalId index, and then stops.

From what I can tell, the `Lease.queryLeases()` method does not implement pagination on queries, which is likely causing the error:
https://github.com/Optum/dce/blob/v0.29.0/pkg/data/leases.go#L14

While our use case had to do with deleting leases, from looking at the code it seems this could effect any database query, as the bug exists in the low level `queryLeases` method. The `queryAccounts` method also appears to be missing pagination.

**Expected behavior**

Matching lease should be deactivated

**Additional context**

**Comment by AmudaPalani** [comment]
it only effects users with more than 25 lease records in our DB
