### ISSUE TITLE
DCE Upgrade

### ISSUE THREAD

**Issue by rafabnunes** [Optum/dce#395]
Hello DCE Community,

I've installed DCE version 0.32.0 last year and now I need to update to the new version 0.33.4.
How can I upgrade in place for latest version ?

Thanks in advance.

Rafael Nunes

**Comment by robologic** [comment]
Hi @rafabnunes, Welcome, and thank you for reaching out to DCE Community. 
You can upgrade to the latest version, 0.33.4. Please grab the code from the master branch Or download the artifacts from the releases. You may want to look at the [release note](https://github.com/Optum/dce/releases) to know what has changed. In addition to these features, a few go packages and aws terraform provider are upgraded, so You might have to resolve these dependencies in your project if you run into issues during deployment. Let us know how your upgrade goes.

**Comment by eric-w-hart** [comment]
Closing this issue. No response or activity on it has taken place since Jan 2021.
