### ISSUE TITLE
Issue provisioning artifacts bucket.

### ISSUE THREAD

**Issue by hsdp-smulford** [Optum/dce#447]
When attempting to deploy an initial DCE environment, via terraform and dce cli, errors were encountered provisioning the bucket aws_s3_bucket.artifacts.

Tailing the ~/.dce/deploy.yaml, the following message is found:
```
Error: Error creating S3 bucket: InvalidBucketAclWithObjectOwnership: Bucket cannot have ACLs set with ObjectOwnership's BucketOwnerEnforced setting
	status code: 400, request id: G9RD2A0CPQ8M89NH, host id: Mb74ejjTNsTH/jk2FXliu/CAqMjbd/1GTfZBrn6sRjSoOG02O1t5RNX0RO6ixF/pSKqSoYRG7AQ=

  on .terraform/modules/dce/modules/artifacts_bucket.tf line 9, in resource "aws_s3_bucket" "artifacts":
   9: resource "aws_s3_bucket" "artifacts" {
```
This issue has been reported and resolved here: https://github.com/hashicorp/terraform-provider-aws/issues/26164#issuecomment-1260995693

I was able to get past the issue by commenting out the following line, defaulting the bucket to private ACL:
https://github.com/Optum/dce/blob/50797d0e8c093a4dfe914c56fdcebd42a435606f/modules/artifacts_bucket.tf#L13

**Comment by iprayforwaves** [comment]
I just ran into this issue as well when installing [AWS Sandboxes. ](https://github.com/awslabs/sandbox-accounts-for-events)

**Comment by bjfish25** [comment]
This issue should have been fixed from this pr: https://github.com/Optum/dce/pull/449 in release 0.35.0.

I'll close this to clean up the repo, but be free to re-open if you find that this is not true
