### ISSUE TITLE
Why the aws-nuke fork?

### ISSUE THREAD

**Issue by hutchic** [Optum/dce#471]
Looking for a similar issue all I found was https://github.com/Optum/dce/issues/312 and when I look at the delta the official aws-nuke more maintained / better supported and so I'm curious why was aws-nuke forked?

I don't doubt there was a reason but I'm not sure I see it anymore which brings me to the second question -- is the fork still necessary? If it is maybe setting up the [github pull bot](https://github.com/wei/pull) or equivalent to help keep the fork more closely sync'd would be a good approach

**Comment by amyschoen** [comment]
This was set up so that the team working on DCE could contribute changes back to AWS Nuke and also start using them before they were officially accepted into the project.  I can't say if this is still needed or not.

**Comment by bjfish25** [comment]
The only reason at the moment is for this Pull request: https://github.com/Optum/aws-nuke/pull/19 for this issue: https://github.com/rebuy-de/aws-nuke/issues/955

In the past it was useful to reference our fork specifically to get the changes before merged into rebuy-de/aws-nuke. Future releases of DCE should hopefully not drift too far away from the original repo
